---
language: c

os:
  - linux
  - osx
  
dist: xenial
addons:
  apt:
    packages:
    - qt5-default
    - qt5-qmake 
    - qtbase5-dev-tools 
    - qttools5-dev-tools
    - build-essential
    - libboost-dev
    - libboost-system-dev
    - libboost-filesystem-dev 
    - libboost-program-options-dev
    - libboost-thread-dev
    - libssl-dev
    - libdb++-dev
    - libminiupnpc-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost berkeley-db miniupnpc; fi
    
script:
  - qmake
  - make
